name: flutter_native_dialog
description: Native dialogs for Flutter in Add2App use cases.
version: 0.0.1
author: Wouter Hardeman <wouterhardeman94@gmail.com>
homepage: https://github.com/wouterhardeman/flutter_native_dialog

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

flutter:
  plugin:
    androidPackage: nl.wouterhardeman.flutternativedialog
    pluginClass: FlutterNativeDialogPlugin
